services:
  streaming-service:
    build:
      context: ./streaming-service
      dockerfile: Dockerfile
    container_name: streaming-service
    ports:
      - '4000:80'
    environment:
      - PORT=80
    restart: 'no'
